import {toCSV} from "../csv";

describe("toCSV", () => {
  it("converts keyed object to CSV", () => {
    const actual = [
      {
        title: "Dientes acrílicos ACRITONE",
        price: 100,
        "options.0.options.0.id": "-VXnHrVfbA",
        "options.0.options.0.title": "61 (A1)",
        "options.0.options.0.price": 0,
        "options.0.options.1.title": "62 (A2) ",
        "options.0.options.1.price": 0,
        "options.0.options.1.id": "sVzI7YwOw3",
        "options.0.options.2.price": 0,
        "options.0.options.2.id": "Z3Hz8RbR-",
        "options.0.options.2.title": "66 (A3)",
        "options.0.options.3.title": "67 (A3.5)",
        "options.0.options.3.price": 0,
        "options.0.options.3.id": "o4Ssyemwu",
        "options.0.options.4.price": 0,
        "options.0.options.4.id": "8kt3_xXFh",
        "options.0.options.4.title": "69 (C3)",
        "options.0.options.5.id": "nUA5hMnMY",
        "options.0.options.5.title": "81 (A4)",
        "options.0.options.5.price": 0,
        "options.0.options.6.id": "QXW8OAtdX",
        "options.0.options.6.title": "B2",
        "options.0.options.6.price": 0,
        "options.0.options.7.price": 0,
        "options.0.options.7.id": "ZKLWFmJAA",
        "options.0.options.7.title": "65",
        "options.0.options.8.price": 0,
        "options.0.options.8.id": "F3rl301hU",
        "options.0.options.8.title": "77 (C4)",
        "options.0.options.9.price": 0,
        "options.0.options.9.id": "HR9TG7ZEL",
        "options.0.options.9.title": "68",
        "options.0.options.10.id": "VJgWvD7fK",
        "options.0.options.10.title": "D2",
        "options.0.options.10.price": 0,
        "options.0.count": 1,
        "options.0.required": true,
        "options.0.title": "Elegir color",
        "options.0.id": "ALd_EULTn",
        "options.1.options.0.id": "b6GMeBOyoH",
        "options.1.options.0.title": "Superior",
        "options.1.options.0.price": 0,
        "options.1.options.1.title": "Inferior",
        "options.1.options.1.price": 0,
        "options.1.options.1.id": "LTOSVTydj8",
        "options.1.count": 1,
        "options.1.required": true,
        "options.1.title": "Elegir ubicación",
        "options.1.id": "x_ueCLLZ-",
        "options.2.options.0.price": 0,
        "options.2.options.0.id": "OHqqTGwL2g",
        "options.2.options.0.title": "18",
        "options.2.options.1.id": "bf5YOFq2tB",
        "options.2.options.1.title": "20",
        "options.2.options.1.price": 0,
        "options.2.options.2.price": 0,
        "options.2.options.2.id": "d6UbcZXC1",
        "options.2.options.2.title": "22",
        "options.2.options.3.price": 0,
        "options.2.options.3.id": "Ra5fejM_0",
        "options.2.options.3.title": "26",
        "options.2.options.4.id": "Xr6CizyRr",
        "options.2.options.4.title": "28",
        "options.2.options.4.price": 0,
        "options.2.options.5.price": 0,
        "options.2.options.5.id": "UJuONdmGOi",
        "options.2.options.5.title": "30",
        "options.2.options.6.id": "QC2BGESc_",
        "options.2.options.6.title": "32",
        "options.2.options.6.price": 0,
        "options.2.options.7.title": "34",
        "options.2.options.7.price": 0,
        "options.2.options.7.id": "tmaoZEt7S0",
        "options.2.options.8.id": "KROQ08qea",
        "options.2.options.8.title": "36",
        "options.2.options.8.price": 0,
        "options.2.options.9.id": "45c0UgSY_",
        "options.2.options.9.title": "36",
        "options.2.options.9.price": 0,
        "options.2.options.10.price": 0,
        "options.2.options.10.id": "Jwu46k011",
        "options.2.options.10.title": "P4",
        "options.2.options.11.title": "P5",
        "options.2.options.11.price": 0,
        "options.2.options.11.id": "NH-pMypeWj",
        "options.2.options.12.title": "P6",
        "options.2.options.12.price": 0,
        "options.2.options.12.id": "uCvNfmUiK",
        "options.2.count": 1,
        "options.2.required": true,
        "options.2.title": "Elegir forma",
        "options.2.id": "j_S9tjvsH",
        image:
          "https://res.cloudinary.com/goncy/image/upload/v1592069274/pency-dev/demo/rbdege8znituaxhsoiel.jpg",
        id: "0ho2ClVuinouD5fIJj4P",
        featured: false,
        description:
          "Dientes de 2 capas Coloracion universal Alta resistencia mecanica Fluorecesncia natural Angulacion de 33º en posteriores Excelente adherencia a resinas bases Aptos para protesis flexibles inyectadas.",
        category: "Zientes acrílicos",
        available: true,
      },
      {
        featured: false,
        category: "Ensaladas",
        image:
          "https://res.cloudinary.com/goncy/image/upload/v1591466642/pency-dev/demo/ahvqjq0wolm7ijp0gioy.jpg",
        price: 25,
        description:
          "Tomate, pepino, cebolla roja, mozzarella fresca, picatostes, albahaca y vinagreta de vino tinto.",
        title: "Ensalada Caprezanella",
        available: true,
        options: [],
        id: "U4DKGoVNsZIKOBAazmtE",
      },
      {
        title: "Ensalada italiana pequeña picada",
        price: 450,
        "options.0.options.0.id": "kZZt1NPD02",
        "options.0.options.0.title": "Pollo",
        "options.0.options.0.price": 0,
        "options.0.options.1.price": 50,
        "options.0.options.1.id": "SxTYYllH5f",
        "options.0.options.1.title": "Panceta",
        "options.0.options.2.id": "WKczZE63C",
        "options.0.options.2.title": "Langostinos",
        "options.0.options.2.price": 100,
        "options.0.options.3.price": 120,
        "options.0.options.3.id": "Fxo53n6ZY",
        "options.0.options.3.title": "Salmón fresco",
        "options.0.count": 1,
        "options.0.required": true,
        "options.0.title": "Carne",
        "options.0.id": "86-RiWS27",
        "options.1.options.0.id": "v-qN7ta4z7",
        "options.1.options.0.title": "Gouda",
        "options.1.options.0.price": 0,
        "options.1.options.1.id": "OIKgL-BhQy",
        "options.1.options.1.title": "Grouyere",
        "options.1.options.1.price": 0,
        "options.1.options.2.id": "1YdmRXnQS",
        "options.1.options.2.title": "Fontina",
        "options.1.options.2.price": 15,
        "options.1.options.3.id": "ZcMqVqgD1",
        "options.1.options.3.title": "Roquefort",
        "options.1.options.3.price": 0,
        "options.1.count": 2,
        "options.1.required": false,
        "options.1.title": "Queso",
        "options.1.id": "z-T7uinad",
        image:
          "https://res.cloudinary.com/goncy/image/upload/v1592055665/pency-dev/demo/cvmedhsgevmkmd35wxzh.jpg",
        id: "4DUivuqhVxgHkLkbF5RJ",
        featured: false,
        description:
          "Lechuga con achicoria, salami, tomate, cebolla, garbanzos, pepperoncini, parmesano y vinagreta.",
        category: "Ensaladas",
        available: true,
      },
      {
        description:
          "Vegetales de campo, pera, gorgonzola, nuez quebradiza y vinagreta de la casa.",
        title: "Ensalada URBN",
        available: true,
        options: [],
        featured: false,
        category: "Ensaladas",
        image:
          "https://res.cloudinary.com/goncy/image/upload/v1592069124/pency-dev/demo/zkjhx094km8dfxkrzind.jpg",
        price: 350,
        id: "FZch6N0WwDelAAsDpCsl",
      },
      {
        title: "Pizza",
        price: 420,
        "options.0.options.0.id": "j1mdxd1U70",
        "options.0.options.0.title": "Chica",
        "options.0.options.0.price": 0,
        "options.0.options.1.id": "_Bf7yhuqD",
        "options.0.options.1.title": "Grande",
        "options.0.options.1.price": 150,
        "options.0.count": 1,
        "options.0.required": false,
        "options.0.title": "Tamaño",
        "options.0.id": "lRdCWQMuj",
        image:
          "https://res.cloudinary.com/goncy/image/upload/v1589385570/pency/b6atjv9syncq8royl9bi.jpg",
        id: "QbDCnIAALjmoJZMlXrjC",
        featured: false,
        description: "Muzarela, jamón, huevo y morrón",
        category: "Pizzas",
        available: true,
      },
      {
        title: "Pizza Cuatro Quesos",
        description: "Pizza Cuatro Quesos",
        available: true,
        options: [],
        featured: false,
        category: "Pizzas",
        image:
          "https://res.cloudinary.com/goncy/image/upload/v1592079072/pency-dev/demo/wlgognu3f62po9yjrfcd.jpg",
        price: 400,
        id: "vVeDgPhgAJKst0FbkbdZ",
      },
      {
        description: "Carne, mozzarella y albahaca",
        title: "Pizza Parisina",
        available: true,
        options: [],
        featured: false,
        id: "gZbp99aMKeh71wvH3Uug",
        category: "Pizzas",
        image:
          "https://res.cloudinary.com/goncy/image/upload/v1592079343/pency-dev/demo/dfmon8yvsp8lc9rjtq8z.jpg",
        price: 440,
      },
      {
        title: "Planta Marantha en cilindro mediano con base de Eucalipto",
        price: 2190,
        "options.0.options.0.title": "Rosa",
        "options.0.options.0.price": 0,
        "options.0.options.0.id": "7j8KjF7Owr",
        "options.0.options.1.id": "eQCarpCHvd",
        "options.0.options.1.title": "Azul",
        "options.0.options.1.price": 0,
        "options.0.options.2.id": "Uuv00yyht",
        "options.0.options.2.title": "Amarillo",
        "options.0.options.2.price": 0,
        "options.0.options.3.id": "uAV5zmb4-",
        "options.0.options.3.title": "Gris",
        "options.0.options.3.price": 0,
        "options.0.options.4.title": "Coral",
        "options.0.options.4.price": 0,
        "options.0.options.4.id": "dFLPqSerAD",
        "options.0.options.5.id": "ZnK_SPtQ4",
        "options.0.options.5.title": "Grafito",
        "options.0.options.5.price": 0,
        "options.0.count": 1,
        "options.0.required": true,
        "options.0.title": "Elegir Color",
        "options.0.id": "zWslRi_h8",
        image:
          "https://res.cloudinary.com/goncy/image/upload/v1592142201/pency-dev/demo/ohxhijduzmbh8r6koghb.jpg",
        id: "X89DsWE71V9cEx5N7sSA",
        featured: false,
        description:
          "La Marantha viene en un cilindro impermeabilizado y pintado a mano. El cilindro está acompañado de un aro de madera de eucalipto con un plato en el centro para contener el agua del riego. La base y el plato no están pegadas a la maceta, por lo que pueden separarse. El tamaño de tu planta puede variar levemente en comparación a la foto. Te la entregamos lista, con un agujero para el correcto drenaje del agua y nuestro mix de tierra que fortalece el crecimiento, el bienestar y la longevidad.",
        category: "Plantas",
        available: true,
      },
      {
        category: "Pastas",
        image:
          "https://res.cloudinary.com/goncy/image/upload/v1590012443/pency-dev/demo/bs8riekvevzhaaan5ehp.jpg",
        price: 150,
        description: "",
        title: "Raviolones de verdes de calabaza",
        available: true,
        options: [],
        featured: false,
        id: "9bRHjGRdJA3AUwRGerV2",
      },
      {
        title: "Set Tiger de cerámica",
        price: 4690,
        "options.0.options.0.id": "twNx4BX3HG",
        "options.0.options.0.title": "Amarillo",
        "options.0.options.0.price": 0,
        "options.0.options.1.title": "Rosa",
        "options.0.options.1.price": 0,
        "options.0.options.1.id": "nkpGG7m5W5",
        "options.0.options.2.id": "4n4OTyiGW3",
        "options.0.options.2.title": "Lavanda",
        "options.0.options.2.price": 0,
        "options.0.options.3.id": "cd-uFXf2bN",
        "options.0.options.3.title": "Verde",
        "options.0.options.3.price": 0,
        "options.0.count": 1,
        "options.0.required": true,
        "options.0.title": "Elegi Color",
        "options.0.id": "s48-rwyF6",
        image:
          "https://res.cloudinary.com/goncy/image/upload/v1592142974/pency-dev/demo/sl5qqmnoataw3xrbaaa9.jpg",
        id: "OtjyUI5gFfCdiv9wlBqZ",
        featured: false,
        description: "Tu set incluye",
        category: "Plantas",
        available: true,
      },
    ];
    const expected = "";

    expect(toCSV(actual)).resolves.toEqual(expected);
  });
});
