import {ClientTenant, ServerTenant} from "./types";

export const DEFAULT_CLIENT_TENANT: Omit<ClientTenant, "id" | "slug"> = {
  phone: "5491173694572",
  color: "cyan",
  title: "Pency - Tu tienda online fácil",
  description: "Armá tu tienda y recibí los pedidos via WhatsApp",
  instagram: "",
  facebook: "",
  twitter: "",
  logo: "",
  banner: "",
  category: "",
  highlight: "",
  fields: [],
  keywords: "pency, tienda, online, whatsapp, delivery, pedidos",
  mercadopago: false,
};

export const DEFAULT_SERVER_TENANT: Omit<ServerTenant, "id" | "slug"> = {
  ...DEFAULT_CLIENT_TENANT,
  mercadopago: {
    token: "",
    refresh: "",
    expiration: null,
  },
};

export const CATEGORIES = [
  {label: "Accesorios para vehículos", value: "vehicle-accessories"},
  {label: "Almacén / Kiosco", value: "warehouse-kiosc"},
  {label: "Arte / Artesanías", value: "art-handicrafts"},
  {label: "Artículos para bebés", value: "baby-articles"},
  {label: "Artículos para mascotas", value: "pet-articles"},
  {label: "Autoservicio / Minimercado", value: "self-service-market"},
  {label: "Bar", value: "bar"},
  {label: "Belleza y cuidado personal", value: "beauty-self-care"},
  {label: "Bicicletería y Motos", value: "bike-shop"},
  {label: "Calzado", value: "foot-wear"},
  {label: "Carnicería", value: "butcher-shop"},
  {label: "Carpintería", value: "carpentry"},
  {label: "Centro de salud", value: "health-center"},
  {label: "Cerrajería", value: "locksmith"},
  {label: "Cervecería", value: "breweries"},
  {label: "Chocolatería", value: "chocolate-shop"},
  {label: "Comida rápida", value: "fast-food"},
  {label: "Concesionaria", value: "dealership"},
  {label: "Cooperativa", value: "cooperative"},
  {label: "Cotillón", value: "cotillon"},
  {label: "Delivery", value: "delivery"},
  {label: "Dietética", value: "dietetics"},
  {label: "Electrodomésticos", value: "home-appliances"},
  {label: "Establecimiento educativo", value: "learn-center"},
  {label: "Estacionamiento", value: "parking-log"},
  {label: "Fábrica de pastas", value: "pasta-factory"},
  {label: "Ferretería", value: "hardware-store"},
  {label: "Flete", value: "freight"},
  {label: "Gomería / Taller mecánico", value: "mechanical-workshop"},
  {label: "Heladería", value: "ice-cream-shop"},
  {label: "Herramientas y construcción", value: "construction"},
  {label: "Herrería y carpintería", value: "blacksmithing-carpentry"},
  {label: "Hipermercado / Mayorista", value: "hypermarket-wholesale"},
  {label: "Hogar y decoración", value: "home-decoration"},
  {label: "Iluminación", value: "illumination"},
  {label: "Imprenta", value: "printing"},
  {label: "Informática", value: "computing"},
  {label: "Inmobiliaria", value: "real-state"},
  {label: "Instrumentos musicales", value: "musical-instruments"},
  {label: "Jardinería", value: "gardening"},
  {label: "Joyería y relojería", value: "jewelry-watches"},
  {label: "Juegos y juguetes", value: "toys"},
  {label: "Lavadero de autos", value: "car-laundry"},
  {label: "Librería", value: "bookshop"},
  {label: "Lubricentro", value: "lubrication-center"},
  {label: "Máquinas expendedoras", value: "vending-machines"},
  {label: "Marroquinería, cueros y pieles", value: "leather-goods"},
  {label: "Mueblería", value: "furniture"},
  {label: "Óptica", value: "optic"},
  {label: "Organización de eventos", value: "event-organization"},
  {label: "Organización sin fines de lucro", value: "ong"},
  {label: "Panadería", value: "bakery"},
  {label: "Peluquería", value: "hairdressing"},
  {label: "Perfumería", value: "perfumery"},
  {label: "Pesca y camping", value: "fishing-camping"},
  {label: "Pescadería", value: "fish-shop"},
  {label: "Pinturería", value: "paint-shop"},
  {label: "Restaurante", value: "restaurant"},
  {label: "Ropa y accesorios", value: "clothes-accessories"},
  {label: "Salud / Farmacia", value: "health-pharmacy"},
  {label: "Servicio de diseño y publicidad", value: "design-advertising-service"},
  {label: "Servicio de fotografía", value: "photography"},
  {
    label: "Servicio de reparación de articulos electrónicos",
    value: "electronic-repair",
  },
  {label: "Servicio informático", value: "computing-service"},
  {label: "Servicios de mensajerías", value: "courier-service"},
  {label: "Servicios de salud", value: "health-service"},
  {label: "Servicios para el hogar", value: "home-service"},
  {label: "Servicios profesionales", value: "professional-service"},
  {label: "Supermercado", value: "supermarket"},
  {label: "Teatro", value: "theater"},
  {label: "Telefonía y electrónica", value: "phone-electronic"},
  {label: "Tintorerías y lavadero", value: "dry-cleaner"},
  {label: "Transporte de pasajeros", value: "passenger-transport"},
  {label: "Venta de autopartes y talleres", value: "auto-parts"},
  {label: "Venta de productos de granja", value: "farm-products"},
  {label: "Verdulería", value: "greengrocery"},
  {label: "Veterinaria", value: "vet"},
  {label: "Viajes y turismo", value: "travel-tourism"},
  {label: "Vinoteca", value: "wines"},
  {label: "Vivero / Florería", value: "flower-shop"},
  {label: "Otro", value: "other"},
];

export const COUNTRIES = [
  {name: "Argentina", code: "AR"},
  {name: "Brazil", code: "BR"},
  {name: "Colombia", code: "CO"},
  {name: "Cuba", code: "CU"},
  {name: "Ecuador", code: "EC"},
  {name: "México", code: "MX"},
  {name: "Paraguay", code: "PY"},
  {name: "Perú", code: "PE"},
  {name: "España", code: "ES"},
  {name: "United States", code: "US"},
  {name: "Uruguay", code: "UY"},
  {name: "Venezuela", code: "VE"},
];
